### GET
DELETE  http://localhost:4004/odata/v4/inventory/serviceRequest/40001

###
GET http://localhost:4004/odata/v4/inventory/StorageLocation?$filter=LocationID eq 'LOC02'


### POST STATUS
PUT http://localhost:4004/odata/v4/inventory/Material_Status/FTR
Content-Type: application/json

{
  "StatusCode":"FTR",
  "Description":"testing10"
}
### GET
GET http://localhost:4004/odata/v4/inventory/rqSubMaterial?$filter=reqNo eq '40002'

###
GET http://localhost:4004/odata/v4/inventory/rqMaterial?$filter=reqNo eq '40001'

###
PUT http://localhost:4004/odata/v4/inventory/rqMaterial(reqNo=40001)
Content-Type: application/json

{
      "Status"	
}
### 
PUT http://localhost:4004/odata/v4/inventory/rqMaterial(reqNo=40001,MaterialCode='MAT01')
Content-Type: application/json

{
      "Category": "B",
      "Description": "pipes and bolts",
      "Quantity": 180,
      "Remarks": "testing"
}

###
POST http://localhost:4004/odata/v4/inventory/rqSubMaterial
Content-Type: application/json

{
          "Category": "D",
          "Description": "Iron Bolt",
          "MaterialCode": "SUB003",
          "Quantity": 100,
          "reqNo"  : 40001,
          "Parent_MaterialCode": "MAT01"
}


### create
POST http://localhost:4004/odata/v4/inventory/serviceRequest
Content-Type: application/json


{  
  "Materials": [
    {
      "Category": "C",
      "MaterialCode": "MAT001",
      "Description": "Steel Pipe",
      "Status": "Active",
      "Remarks": "Urgent Delivery",
      "Quantity": 100,
      "SubcomponentList": [
        {
          "Category": "B",
          "Description": "Steel Fitting",
          "MaterialCode": "SUB001",
          "Quantity": 50,
          "Parent": "MAT001"
        },
        {
          "Category": "C",
          "Description": "Steel Nut",
          "MaterialCode": "SUB002",
          "Quantity": 30,
          "Parent": "MAT001"
        }
      ]
    },
    {
      "Category": "A",
      "MaterialCode": "MAT002",
      "Description": "Iron Rod",
      "Status": "Pending",
      "Remarks": "Standard",
      "Quantity": 200,
      "SubcomponentList": [
        {
          "Category": "D",
          "Description": "Iron Bolt",
          "MaterialCode": "SUB003",
          "Quantity": 100,
          "Parent": "MAT002"
        }
      ]
    }
  ]
}
